// THIS FILE IS GENERATED BY TOOL, PLEASE DON'T EDIT

#include "JSONManager.h"
#include "cocos2d.h"

USING_NS_CC;

#define LOAD_JSON_FILE(FileName) \
    Json::Value json_data = loadFromFile(FileName)

#define LOAD_TABLE_DATA(TableName) \
    JSON_VAR(TableName).load(json_data[#TableName])

JSONManager::JSONManager()
: m_bInited(false)
{0}
{1}

JSONManager::~JSONManager()
{0}
{1}

JSONManager& JSONManager::sharedInstance()
{0}
	static JSONManager s_instance;
	return s_instance;
{1}

void JSONManager::loadData()
{0}
	if (!m_bInited) {0}
		m_bInited = true;
{2}
	{1}
{1}

Json::Value JSONManager::loadFromFile(const char* filename)
{0}
	Data data = CCFileUtils::getInstance()->getDataFromFile(filename);	

    Json::Reader reader;
    Json::Value json_data;
    reader.parse((const char*)data.getBytes(), json_data);
    return json_data;
{1}
