// THIS FILE IS GENERATED BY TOOL, PLEASE DON'T EDIT

#ifndef _JSON_MANAGER_H_
#define _JSON_MANAGER_H_

#include "JSONLoader.h"
#include "JSONData.h"

#define JSON_VAR(TableName)         m_##TableName
#define JSON_DECLARE_VAR(TableName) JSONLoader<TableName##Item> JSON_VAR(TableName)
#define JSON_DATASET(TableName)     JSONManager::sharedInstance().JSON_VAR(TableName)
#define LOAD_JSON_DATA()            JSONManager::sharedInstance().loadData()

class JSONManager
{0}
protected:
	JSONManager();

public:
	~JSONManager();

	static JSONManager& sharedInstance();
	void loadData();

public:
{2}
protected:
	Json::Value loadFromFile(const char* filename);

private:
	bool m_bInited;
{1};

#endif // _JSON_MANAGER_H_
